name: check
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
      - run: nix flake check
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [yambs, seed-nukular]
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
      - run: nix build .#packages.x86_64-linux.${{ matrix.pkg }}
